### ISSUE TITLE
Document project tech stack and goal

### ISSUE THREAD

**Issue by yu204** [ChapmanCPSC/SE-Society#15]
Allow viewers of Github project to see what technology we are using to create the project as well as read about what our end product should be (what the purpose of the web app is) 

Add docker environment documentation

Acceptance criteria: Be able to give a 30 second 'elevator pitch' to describe the purpose and features of the website
Add goal of website and tech stack onto readme

**Comment by xaviablaza** [comment]
I'll quickly add the documentation for the url and send the devs the access credentials individually.
