### ISSUE TITLE
Setup deployment strategy

### ISSUE THREAD

**Issue by xaviablaza** [ChapmanCPSC/SE-Society#19]
## Description

As a developer,
I can deploy to the staging website,
so that the product owner can review and accept my changes

## Acceptance Criteria
Part 1
- Make sure docker hub account is created
- Make circleci build docker image and push it to [Docker Hub](https://hub.docker.com/r/sesociety/se330/)

Part 2
- Draw diagram explaining to developers how the deployment strategy will work

**Comment by xaviablaza** [comment]
To satisfy Part 2 of my acceptance criteria, I've added a wiki page here:
https://github.com/ChapmanCPSC/SE-Society/wiki

You will see a diagram showing the high-level details of our system architecture.

**Comment by yu204** [comment]
I like the diagram :)
