### ISSUE TITLE
Seed data

### ISSUE THREAD

**Issue by yu204** [ChapmanCPSC/SE-Society#70]
## Description
Fill the database with sample data to test logins, including Names, zip codes, emails, address, profession, date registered and passwords. 

## Tasks
- To create a migration to create the table `UserDetails` that has a:
```
t.string zipcode
t.string address
t.string profession
```
- Apply the migration `rails db:migrate`
- Fill the `seeds.rb` with new user details `UserDetails.create!()`

**Comment by nElder03** [comment]
Is there a link to the database? Or...?
